"""Desk theme CSS generation and publish (nce_desk_theme.css → Frappe Desk vars).

Paired module: themes.utils.css_writer (Web site tokens → --nce-* classes and vars).

Shared with css_writer: file write + .hash sidecar + assets_json cache bust — publish
tail only. Content generation is intentionally different: flat DESK_CSS_VARS on :root,
no OKLCH shade scale or theme-bg-* class layer.

See themes/CODE_INDEX.json and plans/REFACTORING_PLAN.md for consolidation notes.
"""
from __future__ import annotations

import hashlib
import json
import os

import frappe

DESK_CSS_VARS = (
    ("primary_color", "--primary-color"),
    ("brand_color", "--brand-color"),
    ("bg_color", "--bg-color"),
    ("fg_color", "--fg-color"),
    ("text_color", "--text-color"),
    ("text_muted", "--text-muted"),
    ("text_light", "--text-light"),
    ("border_color", "--border-color"),
    ("dark_border_color", "--dark-border-color"),
    ("control_bg", "--control-bg"),
    ("control_bg_on_gray", "--control-bg-on-gray"),
    ("btn_default_bg", "--btn-default-bg"),
    ("awesomplete_hover_bg", "--awesomplete-hover-bg"),
    ("btn_height", "--btn-height"),
    ("border_radius", "--border-radius"),
    ("border_radius_lg", "--border-radius-lg"),
    ("border_radius_full", "--border-radius-full"),
    ("g_bar_color", "--g-bar-color"),
    ("g_bar_border", "--g-bar-border"),
    ("g_progress_color", "--g-progress-color"),
    ("g_header_background", "--g-header-background"),
    ("g_row_color", "--g-row-color"),
    ("g_today_highlight", "--g-today-highlight"),
)

DESK_TOKEN_FIELDS = [key for key, _ in DESK_CSS_VARS]


def _load_desk_payload(theme_name: str) -> dict:
    if not theme_name or not frappe.db.exists("NCE Desk Theme", theme_name):
        return {}
    return json.loads(frappe.db.get_value("NCE Desk Theme", theme_name, "theme_json") or "{}")


def _emit_desk_var_block(payload: dict, selector: str = ":root") -> list[str]:
    lines = [f"{selector} {{"]
    for key, css_var in DESK_CSS_VARS:
        value = payload.get(key)
        if value is not None and str(value).strip():
            lines.append(f"\t{css_var}: {value};")
    lines.append("}")
    return lines


def generate_desk_css(base_theme_name: str | None, active_theme_names: list[str] | None) -> str:
    merged = dict(_load_desk_payload(base_theme_name) if base_theme_name else {})
    for name in active_theme_names or []:
        if name:
            merged.update(_load_desk_payload(name))
    lines = [
        "/* Generated by themes.utils.desk_css_writer — do not edit */",
        "",
    ]
    lines.extend(_emit_desk_var_block(merged, ":root"))
    return "\n".join(lines)


def _write_desk_css_file(css: str) -> str:
    app_path = frappe.get_app_path("themes")
    css_dir = os.path.join(app_path, "public", "css")
    os.makedirs(css_dir, exist_ok=True)
    path = os.path.join(css_dir, "nce_desk_theme.css")
    with open(path, "w") as f:
        f.write(css)
    return path


def _write_desk_css_hash_file(css_hash: str) -> str:
    app_path = frappe.get_app_path("themes")
    css_dir = os.path.join(app_path, "public", "css")
    os.makedirs(css_dir, exist_ok=True)
    path = os.path.join(css_dir, "nce_desk_theme.css.hash")
    with open(path, "w") as f:
        f.write(css_hash)
    return path


def _read_desk_css_hash() -> str | None:
    try:
        path = os.path.join(
            frappe.get_app_path("themes"),
            "public",
            "css",
            "nce_desk_theme.css.hash",
        )
        with open(path) as f:
            return f.read().strip() or None
    except OSError:
        return None


def publish_desk_theme(theme_name: str | None = None) -> dict:
    """Rebuild nce_desk_theme.css from current DB state (base merged with Active)."""
    from themes.utils.site_theme_config_helpers import get_site_base_desk_theme_name

    base_name = get_site_base_desk_theme_name()
    if base_name and frappe.db.exists("NCE Desk Theme", base_name):
        pass
    elif theme_name and frappe.db.exists("NCE Desk Theme", theme_name):
        base_name = theme_name
    else:
        base_name = base_name or theme_name

    active_names = frappe.get_all(
        "NCE Desk Theme",
        filters={"status": "Active"},
        pluck="name",
    )
    css = generate_desk_css(base_name, active_names)
    _write_desk_css_file(css)
    css_hash = hashlib.sha1(css.encode("utf-8")).hexdigest()[:8]
    _write_desk_css_hash_file(css_hash)
    frappe.cache.delete_value("assets_json")
    frappe.clear_cache()
    return {"status": "ok", "theme": base_name, "css_hash": css_hash, "bytes": len(css)}
