"""Desk theme CSS generation and publish (nce_desk_theme.css → Frappe Desk vars).

Paired module: themes.utils.css_writer (Web site tokens → --nce-* classes and vars).

Shared with css_writer: css_publish.write_published_css() + assets_json cache bust —
publish tail only. Content generation is intentionally different: flat DESK_CSS_VARS on :root,
no OKLCH shade scale or theme-bg-* class layer.

See themes/CODE_INDEX.json and plans/REFACTORING_PLAN.md for consolidation notes.
"""
from __future__ import annotations

import json
import os

import frappe

from themes.utils.css_publish import write_published_css
from themes.utils.theme_tokens import FONT_REGISTRY, FONT_SUBSETS, FONT_BASE_URL

DESK_CSS_VARS = (
    ("primary_color", "--primary-color"),
    ("brand_color", "--brand-color"),
    ("bg_color", "--bg-color"),
    ("fg_color", "--fg-color"),
    ("text_color", "--text-color"),
    ("text_muted", "--text-muted"),
    ("text_light", "--text-light"),
    ("border_color", "--border-color"),
    ("dark_border_color", "--dark-border-color"),
    ("control_bg", "--control-bg"),
    ("control_bg_on_gray", "--control-bg-on-gray"),
    ("btn_default_bg", "--btn-default-bg"),
    ("awesomplete_hover_bg", "--awesomplete-hover-bg"),
    ("btn_height", "--btn-height"),
    ("border_radius", "--border-radius"),
    ("border_radius_lg", "--border-radius-lg"),
    ("border_radius_full", "--border-radius-full"),
    ("g_bar_color", "--g-bar-color"),
    ("g_bar_border", "--g-bar-border"),
    ("g_progress_color", "--g-progress-color"),
    ("g_header_background", "--g-header-background"),
    ("g_row_color", "--g-row-color"),
    ("g_today_highlight", "--g-today-highlight"),
    # Typography — font_family is handled separately (needs CSS stack conversion)
    ("font_size", "--font-size-base"),
    ("font_weight_body", "--nce-font-weight"),
)

_DESK_FONT_GENERIC: dict[str, str] = {
    "Inter": "sans-serif",
    "Source Sans 3": "sans-serif",
    "Public Sans": "sans-serif",
    "Open Sans": "sans-serif",
    "Roboto": "sans-serif",
    "Nunito": "sans-serif",
    "Source Serif 4": "serif",
    "JetBrains Mono": "monospace",
}


def _desk_font_stack(name: str) -> str | None:
    """Convert a stored font name to a CSS font-family stack, or None for system default."""
    if not name or name == "System Default":
        return None
    generic = _DESK_FONT_GENERIC.get(name, "sans-serif")
    return f"'{name}', {generic}"


def _desk_font_face_blocks(name: str) -> list[str]:
    """Return @font-face rule lines for a registered variable font (both subsets)."""
    entry = FONT_REGISTRY.get(name)
    if not entry:
        return []
    slug = entry[0]
    out: list[str] = []
    for subset, unicode_range in FONT_SUBSETS.items():
        out += [
            "@font-face {",
            f"\tfont-family: '{name}';",
            "\tfont-style: normal;",
            "\tfont-display: swap;",
            "\tfont-weight: 100 900;",
            f"\tsrc: url('{FONT_BASE_URL}/{slug}/{subset}-wght-normal.woff2') format('woff2');",
            f"\tunicode-range: {unicode_range};",
            "}",
        ]
    return out

# font_family is not in DESK_CSS_VARS (needs stack conversion, handled separately in generate_desk_css)
# but it must be in DESK_TOKEN_FIELDS so _desk_parse_payload doesn't strip it on save.
DESK_TOKEN_FIELDS = [key for key, _ in DESK_CSS_VARS] + ["font_family"]

# Frappe v15 Espresso re-declares Desk vars on [data-theme="light"] after app_include_css.
DESK_CSS_SELECTOR = ":root, [data-theme=\"light\"]"


def _load_desk_payload(theme_name: str) -> dict:
    if not theme_name or not frappe.db.exists("NCE Desk Theme", theme_name):
        return {}
    return json.loads(frappe.db.get_value("NCE Desk Theme", theme_name, "theme_json") or "{}")


def _emit_desk_var_block(payload: dict, selector: str = ":root") -> list[str]:
    lines = [f"{selector} {{"]
    for key, css_var in DESK_CSS_VARS:
        value = payload.get(key)
        if value is not None and str(value).strip():
            lines.append(f"\t{css_var}: {value};")
    lines.append("}")
    return lines


def generate_desk_css(base_theme_name: str | None, active_theme_names: list[str] | None) -> str:
    merged = dict(_load_desk_payload(base_theme_name) if base_theme_name else {})
    for name in active_theme_names or []:
        if name:
            merged.update(_load_desk_payload(name))

    lines = [
        "/* Generated by themes.utils.desk_css_writer — do not edit */",
        "",
    ]

    # @font-face blocks for the selected body font (self-hosted variable font)
    font_name = str(merged.get("font_family", "") or "").strip()
    font_stack = _desk_font_stack(font_name) if font_name else None
    if font_name and font_name != "System Default":
        face_lines = _desk_font_face_blocks(font_name)
        if face_lines:
            lines.extend(face_lines)
            lines.append("")

    # Core CSS var block (colors, shape, font-size, font-weight)
    var_block = _emit_desk_var_block(merged, DESK_CSS_SELECTOR)
    # Inject --font-stack before the closing brace when a named font is selected
    if font_stack:
        var_block.insert(-1, f"\t--font-stack: {font_stack};")
    lines.extend(var_block)

    return "\n".join(lines)


def get_desk_theme_css_url() -> str | None:
    """Return the Desk theme CSS asset URL with a fresh cache-buster."""
    css_hash = read_desk_css_hash()
    base_url = "/assets/themes/css/nce_desk_theme.css"
    if css_hash:
        return f"{base_url}?v={css_hash}"
    return base_url


def read_desk_css_hash() -> str | None:
    """Prefer Site Theme Config (updated on every publish); fall back to sidecar file."""
    try:
        desk_hash = frappe.db.get_single_value("Site Theme Config", "desk_css_hash")
        if desk_hash:
            return str(desk_hash).strip() or None
    except Exception:
        pass
    return _read_desk_css_hash()


def _read_desk_css_hash() -> str | None:
    try:
        path = os.path.join(
            frappe.get_app_path("themes"),
            "public",
            "css",
            "nce_desk_theme.css.hash",
        )
        with open(path) as f:
            return f.read().strip() or None
    except OSError:
        return None


def publish_desk_theme(theme_name: str | None = None) -> dict:
    """Rebuild nce_desk_theme.css from current DB state (base merged with Active)."""
    from themes.utils.site_theme_config_helpers import get_site_base_desk_theme_name

    base_name = get_site_base_desk_theme_name()
    if base_name and frappe.db.exists("NCE Desk Theme", base_name):
        pass
    elif theme_name and frappe.db.exists("NCE Desk Theme", theme_name):
        base_name = theme_name
    else:
        base_name = base_name or theme_name

    active_names = frappe.get_all(
        "NCE Desk Theme",
        filters={"status": "Active"},
        pluck="name",
    )
    css = generate_desk_css(base_name, active_names)
    css_hash = write_published_css("nce_desk_theme.css", css)
    frappe.db.set_single_value("Site Theme Config", "desk_css_hash", css_hash)
    frappe.cache.delete_value("assets_json")
    frappe.clear_cache()
    return {"status": "ok", "theme": base_name, "css_hash": css_hash, "bytes": len(css)}
