app_name = "themes"
app_title = "Themes"
app_publisher = "Oliver Reid"
app_description = "Themes — Site-wide theming for Frappe"
app_email = "oliver_reid@me.com"
app_license = "mit"
app_logo_url = "/assets/themes/images/logo.jpg"

# ── Site-wide CSS ────────────────────────────────────────────────────────────
# Theme CSS is generated by publish_theme() and contains
# only :root { --nce-* } custom-property declarations.  It does NOT style
# any Frappe Desk elements — downstream apps opt-in by referencing the tokens.
app_include_css = ["/assets/themes/css/nce_theme.css"]

# SPA route rules — Frappe serves the Vue app for /themes/* paths
website_route_rules = [
	{"from_route": "/themes/<path:app_path>", "to_route": "themes"},
]

add_to_apps_screen = [
	{
		"name": "themes",
		"logo": "/assets/themes/images/logo.jpg",
		"title": "Themes",
		"route": "/app/themes",
	}
]

after_install = "themes.install.after_install"
