app_name = "themes"
app_title = "Themes"
app_publisher = "Oliver Reid"
app_description = "Themes — Site-wide theming for Frappe"
app_email = "oliver_reid@me.com"
app_license = "mit"
app_logo_url = "/assets/themes/images/logo.jpg"

# ── Site-wide CSS ────────────────────────────────────────────────────────────
# Theme CSS is generated by publish_theme() and contains
# only :root { --nce-* } custom-property declarations.  It does NOT style
# any Frappe Desk elements — downstream apps opt-in by referencing the tokens.


def _css_url(css_filename: str) -> str:
    """Return /assets/themes/css/<css_filename> with a ?v=<hash> cache-buster when available.

    The hash is read from the "<css_filename>.hash" sidecar written by the publish
    step. This runs at hooks import time, so it must be DB-free and never raise:
    any problem falls back to the bare path. (A previous approach monkey-patched
    frappe.get_hooks and broke boot — never do that.)
    """
    base_url = f"/assets/themes/css/{css_filename}"
    try:
        import os

        hash_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "public",
            "css",
            f"{css_filename}.hash",
        )
        with open(hash_path) as f:
            css_hash = f.read().strip()
        if css_hash:
            return f"{base_url}?v={css_hash}"
    except Exception:
        pass
    return base_url


app_include_css = [
    _css_url("nce_theme.css"),
    _css_url("nce_desk_theme.css"),
    "/assets/themes/dist/theme-swatch-picker.css",
]

app_include_js = ["/assets/themes/dist/theme-swatch-picker.umd.js"]

# SPA route rules — Frappe serves the Vue app for /themes/* paths
website_route_rules = [
	{"from_route": "/themes/<path:app_path>", "to_route": "themes"},
	{"from_route": "/themes", "to_route": "themes"},
	{"from_route": "/desk-themes/<path:app_path>", "to_route": "themes"},
	{"from_route": "/desk-themes", "to_route": "themes"},
	# Frappe app portal rewrites desk-themes → app-themes for the themes app tile
	{"from_route": "/app-themes/<path:app_path>", "to_route": "themes"},
	{"from_route": "/app-themes", "to_route": "themes"},
]

add_to_apps_screen = [
	{
		"name": "themes",
		"logo": "/assets/themes/images/logo.jpg",
		"title": "Themes",
		"route": "/app/theme-editor",
	},
	{
		"name": "desk-themes",
		"logo": "/assets/themes/images/logo.jpg",
		"title": "Desk Themes",
		"route": "/app/desk-theme-editor",
	},
]

after_install = "themes.install.after_install"
