app_name = "themes"
app_title = "Themes"
app_publisher = "Oliver Reid"
app_description = "Themes — Site-wide theming for Frappe"
app_email = "oliver_reid@me.com"
app_license = "mit"
app_logo_url = "/assets/themes/images/logo.jpg"

# ── Site-wide CSS ────────────────────────────────────────────────────────────
# Theme CSS is generated by publish_theme() and contains
# only :root { --nce-* } custom-property declarations.  It does NOT style
# any Frappe Desk elements — downstream apps opt-in by referencing the tokens.


def _nce_theme_css_url() -> str:
    """Return the theme CSS URL with a ?v=<hash> cache-buster when available.

    The hash is read from a sidecar file written by publish_theme(). This runs at
    hooks import time, so it must be DB-free and never raise: any problem falls
    back to the bare path. (A previous approach monkey-patched frappe.get_hooks
    and broke boot — never do that.)
    """
    base_url = "/assets/themes/css/nce_theme.css"
    try:
        import os

        hash_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "public",
            "css",
            "nce_theme.css.hash",
        )
        with open(hash_path) as f:
            css_hash = f.read().strip()
        if css_hash:
            return f"{base_url}?v={css_hash}"
    except Exception:
        pass
    return base_url


def _nce_desk_theme_css_url() -> str:
    """Return the desk theme CSS URL with a ?v=<hash> cache-buster when available."""
    base_url = "/assets/themes/css/nce_desk_theme.css"
    try:
        import os

        hash_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            "public",
            "css",
            "nce_desk_theme.css.hash",
        )
        with open(hash_path) as f:
            css_hash = f.read().strip()
        if css_hash:
            return f"{base_url}?v={css_hash}"
    except Exception:
        pass
    return base_url


app_include_css = [
    _nce_theme_css_url(),
    _nce_desk_theme_css_url(),
    "/assets/themes/dist/theme-swatch-picker.css",
]

app_include_js = ["/assets/themes/dist/theme-swatch-picker.umd.js"]

# SPA route rules — Frappe serves the Vue app for /themes/* paths
website_route_rules = [
	{"from_route": "/themes/<path:app_path>", "to_route": "themes"},
	{"from_route": "/desk-themes/<path:app_path>", "to_route": "themes"},
]

add_to_apps_screen = [
	{
		"name": "themes",
		"logo": "/assets/themes/images/logo.jpg",
		"title": "Themes",
		"route": "/app/theme-editor",
	},
	{
		"name": "desk-themes",
		"logo": "/assets/themes/images/logo.jpg",
		"title": "Desk Themes",
		"route": "/app/desk-theme-editor",
	},
]

after_install = "themes.install.after_install"
