"""Golden-file regression tests for CSS generation (no Frappe bench required)."""
from __future__ import annotations

import hashlib
import json
import os
import sys
import unittest
from pathlib import Path

from themes.tests.frappe_stub import install_frappe_stub

install_frappe_stub()

from themes.utils.css_writer import generate_css, generate_site_css
from themes.utils.desk_css_writer import _emit_desk_var_block
from themes.utils.theme_color_utils import resolve_neutral_into_payload

TESTS_DIR = Path(__file__).resolve().parent
GOLDEN_DIR = TESTS_DIR / "golden"
DATA_DIR = TESTS_DIR.parent / "data"


def _css_hash(css: str) -> str:
    return hashlib.sha1(css.encode("utf-8")).hexdigest()[:8]


def _desk_css_from_payload(payload: dict) -> str:
    lines = ["/* Generated by themes.utils.desk_css_writer — do not edit */", ""]
    lines.extend(_emit_desk_var_block(payload, ":root"))
    return "\n".join(lines)


def _load_payloads() -> dict:
    with open(DATA_DIR / "base_theme.json") as f:
        default = resolve_neutral_into_payload(json.load(f))

    gamma = dict(default)
    gamma["primary_color_gamma"] = 20
    gamma["primary_color_saturation"] = 120

    warm = resolve_neutral_into_payload({**default, "neutral_color_warmth": 40})

    with open(DATA_DIR / "base_desk_theme.json") as f:
        desk = json.load(f)

    return {
        "default": default,
        "gamma": gamma,
        "warm": warm,
        "desk": desk,
    }


def _golden_cases(payloads: dict) -> dict[str, str]:
    return {
        "web_default.css": generate_css(payloads["default"]),
        "web_gamma_sat.css": generate_css(payloads["gamma"]),
        "web_neutral_warmth.css": generate_css(payloads["warm"]),
        "web_site_default.css": generate_site_css(
            payloads["default"], [("alt", payloads["warm"])]
        ),
        "desk_default.css": _desk_css_from_payload(payloads["desk"]),
    }


class TestCssSnapshots(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.payloads = _load_payloads()
        cls.cases = _golden_cases(cls.payloads)
        if os.environ.get("UPDATE_GOLDEN") == "1":
            GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
            for name, css in cls.cases.items():
                (GOLDEN_DIR / name).write_text(css)
                (GOLDEN_DIR / f"{name}.hash").write_text(_css_hash(css))

    def test_golden_files_exist(self):
        for name in self.cases:
            self.assertTrue(
                (GOLDEN_DIR / name).is_file(),
                f"Missing golden file {name}. Run: UPDATE_GOLDEN=1 python -m unittest themes.tests.test_css_snapshots",
            )
            self.assertTrue(
                (GOLDEN_DIR / f"{name}.hash").is_file(),
                f"Missing golden hash {name}.hash",
            )

    def test_css_byte_stable(self):
        for name, css in self.cases.items():
            golden_path = GOLDEN_DIR / name
            if not golden_path.is_file():
                self.skipTest(f"golden {name} not committed yet")
            golden = golden_path.read_text()
            self.assertEqual(
                css,
                golden,
                f"{name} output changed ({len(css)} vs {len(golden)} bytes). "
                "If intentional, run UPDATE_GOLDEN=1.",
            )

    def test_css_hash_stable(self):
        for name, css in self.cases.items():
            hash_path = GOLDEN_DIR / f"{name}.hash"
            if not hash_path.is_file():
                self.skipTest(f"golden hash for {name} not committed yet")
            expected = hash_path.read_text().strip()
            self.assertEqual(_css_hash(css), expected, f"{name} hash mismatch")


if __name__ == "__main__":
    unittest.main()
